bec_dbt:
  outputs:
    dev:
      dataset: "{{ env_var('TARGET_STAGING_DATASET', 'olist_data_staging') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: service-account
      project: "{{ env_var('BQ_PROJECT_ID') }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      priority: interactive
      threads: 5
      type: bigquery
  target: dev
